version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: >
      sh -c " python3 manage.py migrate && 
              python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/tasks/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A iDare_project worker -l INFO
    volumes:
      - .:/usr/src/tasks
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"
